package com.example.service;

import com.example.entity.Report;
import com.example.repository.ReportRepository;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

/**
 * Report Service - Business logic for report management
 */
@Service
@Slf4j
@Transactional
public class ReportService {

    private final ReportRepository reportRepository;

    public ReportService(ReportRepository reportRepository) {
        this.reportRepository = reportRepository;
    }

    /**
     * Create a new report
     */
    public Report createReport(String reportName, String generatedBy) {
        log.info("Creating new report: {} generated by {}", reportName, generatedBy);
        Report report = new Report();
        report.setReportName(reportName);
        report.setGeneratedBy(generatedBy);
        report.setStatus(Report.ReportStatus.PENDING);
        report.setCreatedAt(LocalDateTime.now());
        return reportRepository.save(report);
    }

    /**
     * Start processing a report
     */
    public Report startProcessing(Long reportId) {
        log.info("Starting processing for report ID: {}", reportId);
        Optional<Report> report = reportRepository.findById(reportId);
        if (report.isPresent()) {
            Report r = report.get();
            r.setStatus(Report.ReportStatus.IN_PROGRESS);
            r.setUpdatedAt(LocalDateTime.now());
            return reportRepository.save(r);
        }
        log.warn("Report not found with ID: {}", reportId);
        return null;
    }

    /**
     * Complete a report with content
     */
    public Report completeReport(Long reportId, String content) {
        log.info("Completing report ID: {}", reportId);
        Optional<Report> report = reportRepository.findById(reportId);
        if (report.isPresent()) {
            Report r = report.get();
            r.setStatus(Report.ReportStatus.COMPLETED);
            r.setReportContent(content);
            r.setCompletedAt(LocalDateTime.now());
            r.setUpdatedAt(LocalDateTime.now());
            return reportRepository.save(r);
        }
        return null;
    }

    /**
     * Mark a report as failed with error details
     */
    public Report failReport(Long reportId, String errorMessage) {
        log.warn("Marking report ID: {} as failed with error: {}", reportId, errorMessage);
        Optional<Report> report = reportRepository.findById(reportId);
        if (report.isPresent()) {
            Report r = report.get();
            r.setStatus(Report.ReportStatus.FAILED);
            r.setErrorMessage(errorMessage);
            r.setCompletedAt(LocalDateTime.now());
            r.setUpdatedAt(LocalDateTime.now());
            return reportRepository.save(r);
        }
        return null;
    }

    /**
     * Get all reports
     */
    public List<Report> getAllReports() {
        return reportRepository.findAll();
    }

    /**
     * Get report by ID
     */
    public Optional<Report> getReportById(Long id) {
        return reportRepository.findById(id);
    }

    /**
     * Get reports by status
     */
    public List<Report> getReportsByStatus(Report.ReportStatus status) {
        return reportRepository.findByStatus(status);
    }

    /**
     * Get recent reports (last N hours)
     */
    public List<Report> getRecentReports(int hours) {
        LocalDateTime startTime = LocalDateTime.now().minusHours(hours);
        return reportRepository.findRecentReports(startTime);
    }

    /**
     * Get count of reports by status
     */
    public long getReportCountByStatus(Report.ReportStatus status) {
        return reportRepository.countByStatus(status);
    }
}
