package com.example.repository;

import com.example.entity.Report;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Report Repository - Data access layer for Report entity
 */
@Repository
public interface ReportRepository extends JpaRepository<Report, Long> {

    /**
     * Find all reports by status
     */
    List<Report> findByStatus(Report.ReportStatus status);

    /**
     * Find all reports generated by specific source
     */
    List<Report> findByGeneratedBy(String generatedBy);

    /**
     * Find reports created after a specific time
     */
    @Query("SELECT r FROM Report r WHERE r.createdAt >= :startTime ORDER BY r.createdAt DESC")
    List<Report> findRecentReports(@Param("startTime") LocalDateTime startTime);

    /**
     * Count reports by status
     */
    long countByStatus(Report.ReportStatus status);

    /**
     * Find failed reports with error message
     */
    List<Report> findByStatusAndErrorMessageIsNotNull(Report.ReportStatus status);
}
